### ISSUE TITLE
Error creating Joint Account - Test network

### ISSUE THREAD

**Issue by schandrakandi** [chatch/stellar-contracts#3]
<img width="841" alt="screen shot 2018-07-01 at 2 07 36 pm" src="https://user-images.githubusercontent.com/25947162/42132579-368dca68-7d38-11e8-976f-ccc8bae18510.png">

**Comment by chatch** [comment]
i'll take a look at this soon. can see it's happening on the hosted version also ...

**Comment by chatch** [comment]
this is fixed now.
